fix `ERROR: File '/usr/share/sandbox-app-launcher/wrapper-script-wx-wx' does not exist.`
Thanks to @TNT_BOM_BOM for the bug report!

https://forums.whonix.org/t/system-wide-sandboxing-framework-sandbox-app-launcher/9008/368

diff --git a/usr/bin/sandbox-app-launcher b/usr/bin/sandbox-app-launcher
--- a/usr/bin/sandbox-app-launcher
+++ b/usr/bin/sandbox-app-launcher
@@ -225,8 +225,8 @@ setup_or_check() {
   fi
 
   ## Check if the second wrapper script exists.
-  if ! [ -f "${wrapper_script}-wx" ]; then
-    echo "ERROR: File '${wrapper_script}-wx' does not exist. This package was not installed properly." >&2
+  if ! [ -f "${wrapper_script}" ]; then
+    echo "ERROR: File '${wrapper_script}' does not exist. This package was not installed properly." >&2
     exit 1
   fi
 
